# Generated by Django 5.0.4 on 2024-08-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('show', 'Show'), ('teatro', 'Apresentação Teatral'), ('orquestra', 'Orquestra'), ('musical', 'Musical'), ('humor', 'Show de Humor'), ('outro', 'Outro')], max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('local', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('cidade', models.CharField(max_length=100)),
                ('quantidade_vagas', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
